#include <limits.h>
#ifndef ENA_GLOBALS
#define ENA_GLOBALS

char ENV_CWD[PATH_MAX];

char SETTINGS_CONTENT_ROOT[PATH_MAX];
char SETTINGS_CONTENT_ROOT_PATH[PATH_MAX];

char SETTINGS_ERROR_HANDLING_404[PATH_MAX];
char SETTINGS_ERROR_HANDLING_500[PATH_MAX];

#endif
